version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "webshop"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g5krb81dbf84"
s3_prefix = "webshop"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"

